name: MetricsHabits
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.habits.svg
          output_action: gist
          config_timezone: Asia/Singapore
          base: ""
          plugin_habits: true
          plugin_habits_charts: yes
          token: ${{ secrets.METRICS_TOKEN }}
