name: MetricsLanguage
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.languages.svg
          output_action: gist
          base: ""
          config_timezone: Asia/Singapore
          plugin_languages: true
          token: ${{ secrets.METRICS_TOKEN }}
